//! Review page semantic message vocabulary shared by keyboard, mouse, and
//! direct update-loop producers.
//!
//! Shell/global commands are intentionally absent. A producer must pass shell
//! precedence before it can create one of these page-local messages.

pub const MousePoint = struct { col: u16, row: u16 };

pub const Msg = union(enum) {
    cancel_search,
    submit_search,
    search_backspace,
    search_move_left,
    search_move_right,
    search_insert: u21,
    /// Borrowed from the synchronous Chasen paste event dispatch.
    search_paste: []const u8,
    cancel_file_search,
    submit_file_search,
    file_search_previous,
    file_search_next,
    file_search_backspace,
    file_search_insert: u21,
    /// Borrowed from the synchronous Chasen paste event dispatch.
    file_search_paste: []const u8,
    focus_sidebar,
    focus_diff,
    sidebar_click_node: usize,
    mouse_sidebar_wheel_up,
    mouse_sidebar_wheel_down,
    mouse_diff_wheel_up,
    mouse_diff_wheel_down,
    mouse_diff_wheel_left,
    mouse_diff_wheel_right,
    mouse_diff_press: MousePoint,
    mouse_diff_drag: ?MousePoint,
    mouse_diff_release: ?MousePoint,
    toggle_focus,
    page_diff_up,
    page_diff_down,
    select_first_file,
    select_last_file,
    clear_search,
    toggle_directory,
    toggle_hunk_fold,
    expand_directory,
    collapse_or_parent_directory,
    scroll_diff_right,
    scroll_diff_left,
    scroll_sidebar_right,
    scroll_sidebar_left,
    scroll_diff_up,
    select_previous_file,
    scroll_diff_down,
    select_next_file,
    enter_search,
    select_next_search_match,
    select_next_hunk,
    select_previous_search_match,
    select_previous_hunk,
    enter_file_search,
    cycle_changed_file_filter,
    toggle_reviewed_file,
    toggle_hide_reviewed_files,
    toggle_sidebar_visibility,
    decrease_sidebar_width,
    increase_sidebar_width,
    enter_commit_panel,
    enter_amend_panel,
    toggle_selected_file,
    toggle_selected_hunk,
    request_discard_selected_file,
    request_push,
    request_pull,
    request_fetch,
    request_branch_switch,
    open_selected_file_in_editor,
    toggle_display_mode,
    toggle_line_numbers,
    copy_current_line,
    copy_current_hunk,
    finish_review_approved,
    finish_review_needs_changes,
    finish_review_canceled,
};
