//! Page-independent semantic message vocabulary for a read-only diff surface.
//!
//! Page adapters may expose a richer superset, but shared update code accepts
//! only these transitions and therefore cannot acquire page-only authority.

const diff_surface = @import("../diff_surface.zig");
const drag_auto_scroll = @import("../drag_auto_scroll.zig");
const selection_action = @import("../selection_action.zig");

pub const Msg = union(enum) {
    cancel_search,
    submit_search,
    search_backspace,
    search_move_left,
    search_move_right,
    search_insert: u21,
    /// Borrowed from the synchronous Chasen paste event dispatch.
    search_paste: []const u8,
    cancel_file_search,
    submit_file_search,
    file_search_previous,
    file_search_next,
    file_search_backspace,
    file_search_insert: u21,
    /// Borrowed from the synchronous Chasen paste event dispatch.
    file_search_paste: []const u8,
    focus_sidebar,
    focus_diff,
    sidebar_click_node: usize,
    mouse_sidebar_wheel_up,
    mouse_sidebar_wheel_down,
    mouse_diff_wheel_up,
    mouse_diff_wheel_down,
    mouse_diff_wheel_left,
    mouse_diff_wheel_right,
    mouse_diff_press: diff_surface.MousePoint,
    mouse_diff_drag: ?diff_surface.MousePoint,
    mouse_diff_release: ?diff_surface.MousePoint,
    mouse_diff_auto_scroll_step: drag_auto_scroll.Step,
    selection_action: selection_action.Action,
    toggle_focus,
    page_diff_up,
    page_diff_down,
    select_first_file,
    select_last_file,
    clear_search,
    toggle_directory,
    toggle_hunk_fold,
    expand_directory,
    collapse_or_parent_directory,
    scroll_diff_right,
    scroll_diff_left,
    scroll_sidebar_right,
    scroll_sidebar_left,
    scroll_diff_up,
    select_previous_file,
    scroll_diff_down,
    select_next_file,
    enter_search,
    select_next_search_match,
    select_next_hunk,
    select_previous_search_match,
    select_previous_hunk,
    enter_file_search,
    cycle_changed_file_filter,
    toggle_reviewed_file,
    toggle_hide_reviewed_files,
    toggle_sidebar_visibility,
    decrease_sidebar_width,
    increase_sidebar_width,
    toggle_display_mode,
    toggle_line_numbers,
};
