#!/usr/bin/env python3
"""Prepare release archives locally or in CI using only the Python standard library."""

import argparse
import gzip
import hashlib
import json
from pathlib import Path
import re
import shutil
import struct
import subprocess
import tarfile
import tempfile


ROOT = Path(__file__).resolve().parent.parent
PLATFORMS = {
    "linux-x86_64": {
        "target": "x86_64-linux.5.15-gnu.2.35",
        "requires": "Linux 5.15 or newer, glibc 2.35 or newer, Git 2.45.1 or newer",
    },
    "macos-arm64": {
        "target": "aarch64-macos.15.0",
        "requires": "macOS 15 or newer, Apple Silicon, Git 2.45.1 or newer",
    },
}


def manifest_version(root=ROOT):
    manifest = (root / "build.zig.zon").read_text()
    match = re.search(r'\.version\s*=\s*"([^"]+)"', manifest)
    if not match or not re.fullmatch(r"(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)", match[1]):
        raise ValueError("build.zig.zon must contain a stable major.minor.patch version")
    return match[1]


def validate_tag(tag, root=ROOT):
    expected = "v" + manifest_version(root)
    if tag is not None and tag != expected:
        raise ValueError(f"tag {tag!r} does not match build.zig.zon ({expected})")
    return expected


def release_notes(tag, root=ROOT):
    tag = validate_tag(tag, root)
    notes = root / ".github/release-notes" / f"{tag}.md"
    if not notes.is_file():
        raise ValueError(f"missing release notes: {notes}")
    if not notes.read_text(encoding="utf-8").strip():
        raise ValueError(f"empty release notes: {notes}")
    return notes


def sha256(file):
    digest = hashlib.sha256()
    with file.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def check_binary(binary, platform):
    with binary.open("rb") as stream:
        header = stream.read(32)
    if platform == "linux-x86_64":
        valid = header[:6] == b"\x7fELF\x02\x01" and len(header) >= 20 and struct.unpack_from("<H", header, 18)[0] == 62
    else:
        valid = header[:4] == b"\xcf\xfa\xed\xfe" and len(header) >= 8 and struct.unpack_from("<I", header, 4)[0] == 0x0100000C
    if not valid:
        raise ValueError(f"{binary} is not a {platform} executable")


def make_archive(stage, archive, timestamp):
    def normalize(info):
        info.uid = info.gid = 0
        info.uname = info.gname = ""
        info.mtime = timestamp
        info.mode = 0o755 if info.isdir() or info.name == f"{stage.name}/gitframe" else 0o644
        return info

    with archive.open("wb") as raw:
        with gzip.GzipFile(filename="", mode="wb", fileobj=raw, mtime=timestamp) as compressed:
            with tarfile.open(fileobj=compressed, mode="w") as bundle:
                bundle.add(stage, arcname=stage.name, filter=normalize)


def smoke_test(archive, version):
    with tempfile.TemporaryDirectory(prefix="gitframe-release-smoke-") as temporary:
        directory = Path(temporary)
        with tarfile.open(archive) as bundle:
            # Only extract the archive generated by this script.
            bundle.extractall(directory)
        executable = directory / archive.name.removesuffix(".tar.gz") / "gitframe"
        output = subprocess.check_output([str(executable), "--version"], text=True, cwd=directory).strip()
        if output != f"gitframe {version}":
            raise ValueError(f"unexpected --version output: {output!r}")
        help_text = subprocess.check_output([str(executable), "--help"], text=True, cwd=directory)
        if "--version" not in help_text:
            raise ValueError("--help did not contain the expected options")


def package(args):
    tag = validate_tag(args.tag)
    version = tag[1:]
    binary = args.binary.resolve()
    check_binary(binary, args.platform)
    args.output.mkdir(parents=True, exist_ok=True)
    name = f"gitframe-{tag}-{args.platform}"
    archive = args.output / f"{name}.tar.gz"
    timestamp = int(subprocess.check_output(["git", "show", "-s", "--format=%ct", "HEAD"], cwd=ROOT, text=True))
    with tempfile.TemporaryDirectory(prefix="gitframe-package-") as temporary:
        stage = Path(temporary) / name
        stage.mkdir()
        shutil.copyfile(binary, stage / "gitframe")
        for document in ("README.md", "LICENSE"):
            shutil.copyfile(ROOT / document, stage / document)
        shutil.copytree(ROOT / "docs", stage / "docs")
        (stage / "BUILD-INFO.json").write_text(json.dumps({
            "version": version,
            "commit": subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=ROOT, text=True).strip(),
            "zig": subprocess.check_output(["zig", "version"], text=True).strip(),
            "platform": args.platform,
            "target": PLATFORMS[args.platform]["target"],
            "cpu": "baseline",
            "optimize": "ReleaseSafe",
            "requires": PLATFORMS[args.platform]["requires"],
        }, indent=2) + "\n")
        make_archive(stage, archive, timestamp)
    smoke_test(archive, version)
    archive.with_name(archive.name + ".sha256").write_text(f"{sha256(archive)}  {archive.name}\n")
    print(archive)


def checksums(directory, tag):
    expected = [f"gitframe-{tag}-{platform}.tar.gz" for platform in PLATFORMS]
    actual = sorted(file.name for file in directory.glob("*.tar.gz"))
    if actual != sorted(expected):
        raise ValueError(f"expected exactly {expected}, found {actual}")
    lines = []
    for name in expected:
        archive = directory / name
        if archive.stat().st_size == 0:
            raise ValueError(f"empty archive: {archive}")
        line = f"{sha256(archive)}  {name}\n"
        if archive.with_name(name + ".sha256").read_text() != line:
            raise ValueError(f"archive checksum mismatch: {name}")
        lines.append(line)
    (directory / "SHA256SUMS").write_text("".join(lines))


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    commands = parser.add_subparsers(dest="command", required=True)
    version_parser = commands.add_parser("version")
    version_parser.add_argument("--tag")
    notes_parser = commands.add_parser("notes", help="validate and locate the release notes for a tag")
    notes_parser.add_argument("--tag", required=True)
    package_parser = commands.add_parser("package")
    package_parser.add_argument("--tag")
    package_parser.add_argument("--platform", choices=PLATFORMS, required=True)
    package_parser.add_argument("--binary", type=Path, required=True)
    package_parser.add_argument("--output", type=Path, required=True)
    checksum_parser = commands.add_parser("checksums")
    checksum_parser.add_argument("--tag", required=True)
    checksum_parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    try:
        tag = validate_tag(args.tag)
        if args.command == "version":
            print(f"tag={tag}")
        elif args.command == "notes":
            print(release_notes(tag))
        elif args.command == "package":
            package(args)
        else:
            checksums(args.output, tag)
    except (ValueError, OSError, subprocess.CalledProcessError, tarfile.TarError) as error:
        parser.exit(1, f"release: {error}\n")


if __name__ == "__main__":
    main()
